/* The report's "analysis as Python": a script for the published cufsm-rs-py package (import
   cufsm_rs, the same Rust engine the page runs) that rebuilds the model on screen and runs the
   same analysis. The model goes over as CUFSM's own tables, row for row, with node and element
   numbers 1-based and every value at full precision (JavaScript's shortest round-trip form, which
   Python reads back to the same double), so an edited or pasted model is reproduced exactly. The
   minima are found as the page finds them (js/results.js findMinima), not by the package's own
   parabola-refined minima, so the printed numbers are the page's. */
const num = (v) => String(Number(v));
const row = (r) => `[${r.map(num).join(', ')}]`;
const rows = (name, comment, list) => list.length
  ? `${name} = [  # ${comment}\n${list.map((r) => `    ${row(r)},`).join('\n')}\n]`
  : `${name} = []  # ${comment}`;

/* The page's model as CUFSM's tables, 1-based: what cufsm_rs.Model takes. */
export function cufsmTables(m) {
  return {
    prop: m.mats.map((q) => [q.id, q.ex, q.ey, q.vx, q.vy, q.g]),
    node: m.nodes.map((n, k) => [k + 1, n.x, n.z, ...n.free.map((f) => (Number(f) ? 1 : 0)), n.stress]),
    elem: m.elems.map((e, k) => [k + 1, e.i + 1, e.j + 1, e.t, e.mat]),
    // the page's spring row is [node i, node j (-1 = ground), ku, kv, kw, kq, local, discrete, ys],
    // 0-based; CUFSM's adds a row number and counts nodes from 1, with node j = 0 for ground
    springs: m.springs.map((r, k) => [k + 1, r[0] + 1, r[1] < 0 ? 0 : r[1] + 1, ...r.slice(2)]),
    constraints: m.constraints.map((r) => [r[0] + 1, r[1], r[2], r[3] + 1, r[4]]),
  };
}

export function pythonScript({ model, solution, bc, terms, lengths }) {
  const { prop, node, elem, springs, constraints } = cufsmTables(model);
  const general = solution === 'general';
  const run = general
    ? `res = cufsm_rs.strip(model, lengths, m_all=${terms}, bc="${bc}", neigs=1)   # terms 1..${terms} at every length`
    : 'res = cufsm_rs.signature(model, lengths)   # S-S, one half-wave at each half-wavelength';
  const word = general ? 'physical lengths' : 'half-wavelengths';
  return `# CivilKit Buckling (CUFSM): the analysis on screen, as a script for cufsm-rs-py
# Generated by CivilKit Buckling (https://mageengineering.com.au/apps/buckling/)
#   pip install cufsm-rs-py
# The model is the page's own, table for table (CUFSM's prop, node and elem, numbered from 1).
# Units: the model's own consistent set (the page labels lengths mm and stresses MPa).
import cufsm_rs

${rows('prop', 'mat#, Ex, Ey, vx, vy, G', prop)}
${rows('node', 'node#, x, z, xdof, zdof, ydof, qdof, stress', node)}
${rows('elem', 'elem#, nodei, nodej, t, mat#', elem)}
${rows('springs', '#, nodei, nodej (0 = ground), ku, kv, kw, kq, local, discrete, ys', springs)}
${rows('constraints', 'node#e, dofe, coeff, node#k, dofk', constraints)}
model = cufsm_rs.Model(prop=prop, node=node, elem=elem,
                       springs=springs or None, constraints=constraints or None)

# the ${lengths.length} ${word} from the page's length list
lengths = [${lengths.map(num).join(', ')}]
${run}
lf = list(res.curve)   # the lowest load factor at each length


def minima(L, f):
    """The page's minima: every interior local minimum, a still-falling last point, and for a
    curve with neither, its lowest point."""
    out = [i for i in range(1, len(f) - 1) if f[i] <= f[i - 1] and f[i] < f[i + 1]]
    if len(f) > 1 and f[-1] < f[-2]:
        out.append(len(f) - 1)
    if not out:
        out = [min(range(len(f)), key=lambda i: f[i])]
    return [(L[i], f[i]) for i in out]


ref = max(abs(n[7]) for n in node)   # the reference stress: the largest nodal stress
for L, f in minima(lengths, lf):
    print(f"L = {L:.6g} mm   load factor {f:.12g}   sigma_cr = {f * ref:.6g} MPa")
`;
}
