/* The device's copy of the full runtime (Pyodide): one Cache Storage cache per pinned release,
   apart from the app's precache (sw.js's ckb-<release>), so the base app's download and size are
   unchanged and a new app release keeps it. Files join it only once the user has agreed to their
   download (js/py/pyodide-worker.js stores what it fetches); sw.js answers from it, offline too.

   PY_CACHE           the cache's name (sw.js, generated by tools/precache.mjs, uses the same)
   indexUrl()         where the app serves the release: vendor/pyodide/<version>/
   cachedFiles()      the release's file names in the cache now (a Set; empty without Cache Storage)
   forgetPyodide()    deletes the cache (every release's) */
import { PYODIDE } from './pyodide-files.js';

export const PY_CACHE_PREFIX = 'ckpy-';
export const PY_CACHE = PY_CACHE_PREFIX + PYODIDE.version;
export const indexUrl = () => new URL(`../../${PYODIDE.dir}`, import.meta.url).href;

export async function cachedFiles() {
  const have = new Set();
  try {
    if (typeof caches === 'undefined' || !(await caches.has(PY_CACHE))) return have;
    const c = await caches.open(PY_CACHE);
    const base = indexUrl();
    for (const req of await c.keys()) {
      const u = req.url.split(/[?#]/)[0];
      if (u.startsWith(base) && Object.hasOwn(PYODIDE.files, u.slice(base.length))) have.add(u.slice(base.length));
    }
  } catch { /* no Cache Storage here */ }
  return have;
}

export async function forgetPyodide() {
  try {
    for (const k of await caches.keys()) if (k.startsWith(PY_CACHE_PREFIX)) await caches.delete(k);
  } catch { /* nothing to forget */ }
}
