/* CivilKit Buckling's offline service worker. Generated by tools/precache.mjs: do not edit.
   Run npm run precache after changing any file the page loads. */
const VERSION = 'c9b3fea45f09';
const FILES = [
 "./",
 "index.html",
 "manifest.webmanifest",
 "styles.css",
 "app.js",
 "cufsm.wasm",
 "styles/shell.css",
 "js/draw.js",
 "js/engine-client.js",
 "js/engine.js",
 "js/ext/builder.js",
 "js/ext/capabilities.js",
 "js/ext/client.js",
 "js/ext/examples.js",
 "js/ext/pyhighlight.js",
 "js/ext/runtime.js",
 "js/ext/ui.js",
 "js/ext/worker.js",
 "js/fullview.js",
 "js/gestures.js",
 "js/history.js",
 "js/labels.js",
 "js/lengths.js",
 "js/model.js",
 "js/numfield.js",
 "js/projects.js",
 "js/pwa.js",
 "js/py/console-client.js",
 "js/py/console-ui.js",
 "js/py/console-worker.js",
 "js/py/detect.js",
 "js/py/dispatch.js",
 "js/py/examples.js",
 "js/py/figures.js",
 "js/py/lite.js",
 "js/py/pyodide-cache.js",
 "js/py/pyodide-files.js",
 "js/py/pyodide-runner.js",
 "js/py/pyodide-worker.js",
 "js/py/runner.js",
 "js/py/transport.js",
 "js/python.js",
 "js/results.js",
 "js/shapefn.js",
 "js/shapes.js",
 "js/share.js",
 "js/shell.js",
 "js/theme.js",
 "js/vlist.js",
 "js/worker.js",
 "py/cufsm-rs-py/cufsm_rs/__init__.py",
 "py/cufsm-rs-py/cufsm_rs/_display.py",
 "py/cufsm-rs-py/cufsm_rs/plot.py",
 "py/cufsm_rs_lite/__init__.py",
 "py/cufsm_rs_lite/plot.py",
 "py/examples/catalogue_check.py",
 "py/examples/distortional_mode.py",
 "py/examples/dsm.py",
 "py/examples/dsm_lip_study.py",
 "py/examples/end_conditions.py",
 "py/examples/full/lightest_numpy.py",
 "py/examples/full/lip_study_plots.py",
 "py/examples/full/readme_quickstart.py",
 "py/examples/lightest_section.py",
 "py/pyodide/_native_js.py",
 "py/pyodide/console.py",
 "py/pyodide/mpl_backend.py",
 "vendor/civilkit/fflate.js",
 "vendor/civilkit/host.js",
 "vendor/civilkit/micropython.mjs",
 "vendor/civilkit/micropython.wasm",
 "vendor/civilkit/registry.js",
 "store/civilkit.dsm-compression.ckext",
 "store/civilkit.section-rounded-cz.ckext",
 "store/civilkit.thickness-study.ckext",
 "store/index.json",
 "guide/",
 "guide/capabilities.html",
 "guide/cli.html",
 "guide/console.html",
 "guide/engine-api.html",
 "guide/examples.html",
 "guide/faq.html",
 "guide/files/yield-and-local.ckext",
 "guide/guide.css",
 "guide/guide.js",
 "guide/img/tutorial-run.png",
 "guide/img/tutorial-test.png",
 "guide/index.html",
 "guide/python-api.html",
 "guide/reference-modules.html",
 "guide/runtimes.html",
 "guide/tutorial.html",
 "guide/ui.html",
 "guide/using.html",
 "guide/worked-examples.html",
 "icons/192.png",
 "icons/512.png",
 "icons/apple-touch-180.png",
 "icons/icon.svg",
 "icons/maskable-512.png",
 "icons/maskable.svg"
];
const PY_DIR = 'vendor/pyodide/314.0.7/', PY_CACHE = 'ckpy-314.0.7', PY_PREFIX = 'ckpy-';

const CACHE = 'ckb-' + VERSION;
const BASE = new URL('./', self.location).href;
const abs = (f) => new URL(f, BASE).href;
// the full Python runtime (Pyodide): its own cache, filled by the console once the user agrees
const PY_BASE = abs(PY_DIR);
const GUIDE = abs('guide/');

self.addEventListener('install', (e) => e.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  await Promise.all(FILES.map(async (f) => {
    // the version in the query and cache: 'reload' get past every HTTP cache on the way
    const res = await fetch(abs(f) + '?sw=' + VERSION, { cache: 'reload' });
    if (!res.ok) throw new Error(f + ': ' + res.status);
    // a host that redirects index.html to ./ gives a redirected response, which a navigation
    // must not be answered with: keep the body and headers only
    await cache.put(abs(f), res.redirected
      ? new Response(await res.blob(), { status: res.status, statusText: res.statusText, headers: res.headers })
      : res);
  }));
})()));

self.addEventListener('activate', (e) => e.waitUntil((async () => {
  for (const k of await caches.keys())
    if ((k.startsWith('ckb-') && k !== CACHE) || (k.startsWith(PY_PREFIX) && k !== PY_CACHE)) await caches.delete(k);
  await self.clients.claim();
})()));

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || !req.url.startsWith(BASE)) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // the guide is documentation with no update prompt: the network first, so a reader sees the
    // pages deployed now, and the cached copy only offline
    if (req.url.startsWith(GUIDE)) {
      try { const res = await fetch(req); if (res.ok) return res; } catch { /* offline: the cache below */ }
    }
    const hit = await cache.match(req, { ignoreSearch: true, ignoreVary: true });
    if (hit) return hit;
    if (req.url.startsWith(PY_BASE)) {
      const py = await (await caches.open(PY_CACHE)).match(req, { ignoreSearch: true, ignoreVary: true });
      if (py) return py;
    }
    // a folder asked for as its index.html, or the other way round
    const path = new URL(req.url).pathname;
    const alt = path.endsWith('/') ? path + 'index.html' : path.endsWith('/index.html') ? path.slice(0, -10) : null;
    const alias = alt && await cache.match(new URL(alt, req.url).href, { ignoreSearch: true, ignoreVary: true });
    return alias || fetch(req);
  })());
});

self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });
